apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  volumes:
  - name: pv-pod
    persistentVolumeClaim:
      claimName: pvc
  containers:
  - image: nginx
    name: pod1
    args:
      - /bin/sh
      - -c
      - sleep 100
    volumeMounts:
    - mountPath: "/data/nginx"
      name: pv-pod
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
