apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: args
  name: args
spec:
  containers:
  - image: nginx
    name: args
    resources: {}
    args:
      - /bin/sh
      - -c
      - sleep 100
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
