apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar
  name: sidecar
spec:
  initContainers:
  - image: busybox
    name: sidecareg
    restartPolicy: Always
    command: ["sleep", "120"]
  containers:
  - image: busybox
    name: sidecar
    command: ["sleep", "120"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
