apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myfirstdeployment
  name: myfirstdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myfirstdeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myfirstdeployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
