apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 10Gi
        cpu: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
