apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tolerationexample
  name: tolerationexample
spec:
  containers:
  - image: busybox
    name: tolerationexample
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
    - key: "effect"
      value: "key"
      operator: "Equal"
      effect: "NoSchedule"
status: {}
