apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    livenessProbe:
      exec:
        command:
          - cat
          - /dev/test
    args:
      - /bin/sh
      - -c
      - touch /dev/test; sleep 30; rm -rf /dev/test; sleep 100
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
